services:
  stats-server:
    container_name: stats-server
    build: ./stats/stats-server
    ports:
      - "9090:9090"
    depends_on:
      stats-db:
        condition: service_started
    environment:
      - DB_NAME=stats
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - DB_HOST=stats-db
      - DB_PORT=5432

  stats-db:
    container_name: stats-db
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - myapp:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test

  ewm-service:
    ports:
      - "8080:8080"

  ewm-db:
    image: postgres:14-alpine