services:
  stats-server:
    container_name: stats-server
    build: ./stats/stats-server
    ports:
      - "9090:9090"
    depends_on:
      stats-db:
        condition: service_healthy
    environment:
      - DB_NAME=stats
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - DB_HOST=stats-db
      - DB_PORT=5432

  stats-db:
    container_name: stats-db
    image: postgres:14-alpine
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test

  ewm-service:
    ports:
      - "8080:8080"

  ewm-db:
    image: postgres:14-alpine