services:
  stats-server:
    container_name: stats-server
    build: ./stats/stats-server
    ports:
      - "9090:9090"
    depends_on:
      stats-db:
        condition: service_healthy
    environment:
      - DB_NAME=stats
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - DB_HOST=stats-db
      - DB_PORT=5432

  stats-db:
    container_name: stats-db
    image: postgres:14-alpine
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test

  ewm-service:
    container_name: ewm-service
    build: ./main-service
    ports:
      - "8080:8080"
    depends_on:
      ewm-db:
        condition: service_healthy
    environment:
      - DB_NAME=ewm
      - DB_HOST=ewm-db
      - DB_PORT=5432
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - STATS_SERVER_URL=http://stats-server:9090

  ewm-db:
    container_name: ewm-db
    image: postgres:14-alpine
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "6432:5432"
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test